server:
  port: 8000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/reports-realm

logging:
  level:
    org.springframework.security: TRACE
    root: TRACE